//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public string CodArt { get; set; }
        public string NomArt { get; set; }
        public int PrecioArt { get; set; }
        public System.DateTime FechaVtoArt { get; set; }
        public string TipoPArt { get; set; }
        public int TamArt { get; set; }
        public bool Activo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
