//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion
    {
        public int NumVent { get; set; }
        public int NumEst { get; set; }
        public Nullable<System.DateTime> FyHEst { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
